version: '3.7'

# Single node single drive for demo purposes. No data persistence implemented.

services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2024-05-07T06-41-25Z
    hostname: minio
    volumes:
      - data1:/data1
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address :9001 /data1
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data1: