name: Docker build and push to Docker hub 

on: 
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
    
          - name: Cache Docker layers
            uses: actions/cache@v3
            with:
              path: /tmp/.buildx-cache
              key: ${{ runner.os }}-buildx-${{ github.sha }}
              restore-keys: |
                ${{ runner.os }}-buildx-
    
          - name: Set up QEMU for multi-platform builds
            uses: docker/setup-qemu-action@v2
    
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/rag_app:latest
              platforms: linux/amd64,linux/arm64
    